# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosGistagram' do
  use_frameworks!
   platform :ios, '15.0'
   pod 'shared', :path => '../shared'
   pod 'SDWebImageSwiftUI'
   pod 'KMPNativeCoroutinesAsync','0.12.2'

 end

 post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
     end
   end

end
