name: Build # name of the workflow

on:
  pull_request: # specifies events to trigger the workflow
    branches: [ main, develop ] # branches that trigger the workflow

jobs: # groups the jobs to be executed in this workflow

  build: # defines a job called build
    name: 🔨 Build # [optional] name of the job
    runs-on: ubuntu-latest # the job will be executed on ubuntu runner. Other include: Microsoft Windows & MacOS runners
    steps: # groups together all the steps that run in build job

      - name: Checkout code # [optional] specifies the name of the step
        uses: actions/checkout@v2 # specifies which version of action to run

      # Setup JDK Version 11 in the runner
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Allow permissions to make gradle executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew build

      # Caches gradle build
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            - name: Build with Gradle
            run: bash ./gradlew build

